/** Chinese brand/model → English lookup for 17VIN API vehicle data. */
const ZH_BRAND_MAP: Record<string, string> = {
  "现代": "Hyundai",
  "北京现代": "Hyundai (Beijing)",
  "起亚": "KIA",
  "东风悦达起亚": "KIA (Dongfeng)",
  "丰田": "Toyota",
  "一汽丰田": "Toyota (FAW)",
  "广汽丰田": "Toyota (GAC)",
  "本田": "Honda",
  "广汽本田": "Honda (GAC)",
  "东风本田": "Honda (Dongfeng)",
  "日产": "Nissan",
  "东风日产": "Nissan (Dongfeng)",
  "马自达": "Mazda",
  "一汽马自达": "Mazda (FAW)",
  "长安马自达": "Mazda (Changan)",
  "三菱": "Mitsubishi",
  "广汽三菱": "Mitsubishi (GAC)",
  "斯巴鲁": "Subaru",
  "铃木": "Suzuki",
  "长安铃木": "Suzuki (Changan)",
  "大众": "Volkswagen",
  "一汽大众": "Volkswagen (FAW)",
  "上汽大众": "Volkswagen (SAIC)",
  "奥迪": "Audi",
  "一汽奥迪": "Audi (FAW)",
  "宝马": "BMW",
  "华晨宝马": "BMW (Brilliance)",
  "奔驰": "Mercedes-Benz",
  "北京奔驰": "Mercedes-Benz (Beijing)",
  "福特": "Ford",
  "长安福特": "Ford (Changan)",
  "雪佛兰": "Chevrolet",
  "上汽通用雪佛兰": "Chevrolet (SAIC-GM)",
  "别克": "Buick",
  "上汽通用别克": "Buick (SAIC-GM)",
  "凯迪拉克": "Cadillac",
  "雷克萨斯": "Lexus",
  "英菲尼迪": "Infiniti",
  "讴歌": "Acura",
  "沃尔沃": "Volvo",
  "路虎": "Land Rover",
  "捷豹": "Jaguar",
  "保时捷": "Porsche",
  "法拉利": "Ferrari",
  "兰博基尼": "Lamborghini",
  "玛莎拉蒂": "Maserati",
  "阿斯顿马丁": "Aston Martin",
  "宾利": "Bentley",
  "劳斯莱斯": "Rolls-Royce",
  "迷你": "MINI",
  "雷诺": "Renault",
  "标致": "Peugeot",
  "东风标致": "Peugeot (Dongfeng)",
  "雪铁龙": "Citroën",
  "东风雪铁龙": "Citroën (Dongfeng)",
  "菲亚特": "FIAT",
  "阿尔法罗密欧": "Alfa Romeo",
  "斯柯达": "Skoda",
  "双龙": "SsangYong",
  "吉普": "Jeep",
  "克莱斯勒": "Chrysler",
  "道奇": "Dodge",
  "林肯": "Lincoln",
  "特斯拉": "Tesla",
  "比亚迪": "BYD",
  "长城": "Great Wall",
  "哈弗": "Haval",
  "吉利": "Geely",
  "奇瑞": "Chery",
  "长安": "Changan",
  "五菱": "Wuling",
  "宝骏": "Baojun",
  "东风": "Dongfeng",
  "一汽": "FAW",
  "上汽": "SAIC",
  "广汽": "GAC",
  "途胜": "Tucson",
  "胜达": "Santa Fe",
  "伊兰特": "Elantra",
  "索纳塔": "Sonata",
  "名图": "Mistra",
  "瑞纳": "Verna",
  "朗动": "Elantra",
  "途观": "Tiguan",
  "帕萨特": "Passat",
  "迈腾": "Magotan",
  "速腾": "Sagitar",
  "宝来": "Bora",
  "高尔夫": "Golf",
  "卡罗拉": "Corolla",
  "凯美瑞": "Camry",
  "雅阁": "Accord",
  "思域": "Civic",
  "飞度": "Fit",
  "逍客": "Qashqai",
  "奇骏": "X-Trail",
  "天籁": "Altima/Teana",
  "轩逸": "Sylphy/Sentra",
  "福克斯": "Focus",
  "蒙迪欧": "Mondeo",
  "翼虎": "Kuga/Escape",
  "锐界": "Edge",
  "前轮毂总成": "Front wheel hub assembly",
  "后轮毂总成": "Rear wheel hub assembly",
};

export function translateZh(text: string): string {
  if (!text) return text;
  const direct = ZH_BRAND_MAP[text];
  if (direct) return direct;
  for (const [zh, en] of Object.entries(ZH_BRAND_MAP)) {
    if (text.includes(zh)) return text.replace(zh, en);
  }
  return text;
}
